services:
  app:
    image: ghcr.io/reversed-r/todoroki-server:latest
    restart: always
    networks:
      - app-network
      - traefik
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik"
      traefik.http.services.app.loadbalancer.server.scheme: http
      traefik.http.services.app.loadbalancer.server.port: 8080
      traefik.http.routers.app.rule: Host(`todo-api.reversed-r.dev`)
      traefik.http.routers.app.entrypoints: websecure,web
      traefik.http.routers.app.tls.certResolver: leresolver
      traefik.http.routers.app.service: app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - APP_DEFAULT_OWNER_EMAIL=${APP_DEFAULT_OWNER_EMAIL}

  postgres:
    image: postgres:17-bullseye
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOSTNAME=${POSTGRES_HOSTNAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: always
    networks:
      - app-network
    healthcheck:
      test: pg_isready -U "${POSTGRES_USER}" || exit 1
      interval: 5s
      timeout: 3s
      retries: 5

  migration:
    build:
      dockerfile: migration.Dockerfile
      context: .
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}

networks:
  app-network:
  traefik:
    name: traefik
    external: true

volumes:
  postgres-data:
