[package]
name = "todoroki-use-case"
version.workspace = true
edition.workspace = true

[dependencies]
todoroki-domain = { path = "../todoroki-domain"}

thiserror.workspace = true
jsonwebtoken.workspace = true
serde.workspace = true
uuid.workspace = true
